#!/usr/bin/env python3
"""Keep ops/quality_audit.py's product-identity rule identical to the bot's.

Why this exists: the auditor has to answer the same question the bot answers -
"is this post the same product as that one?" - and an auditor working from a
different rule can only invent findings. Copying the block by hand is how rules
drift, so the block is copied BY THIS FILE, and `--check` (run from
test_line_fidelity.py) turns any drift into a failing test instead of a surprise
six months later on the live channel.

Usage:  python3 ops/sync_identity.py          # rewrite the auditor's copy
        python3 ops/sync_identity.py --check  # exit 1 when it is out of date
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOT = ROOT / "bestgaa" / "main_bot_new.py"
AUDIT = ROOT / "ops" / "quality_audit.py"
BEGIN = "# >>> BEGIN SYNCED product-identity (generated by ops/sync_identity.py)"
END = "# <<< END SYNCED product-identity"


def bot_block() -> str:
    text = BOT.read_text(encoding="utf-8")
    match = re.search(r"^_SIG_STOP_WORDS = frozenset\(.*?^# <<< IDENTITY-END\n",
                      text, re.S | re.M)
    if not match:
        raise SystemExit("sync_identity: the bot's identity block is not delimited "
                         "any more - fix the markers in bestgaa/main_bot_new.py")
    block = match.group(0).replace("# <<< IDENTITY-END\n", "").rstrip("\n")
    # Same rule, prefixed names, so the auditor can still be read/edited on its own
    # and a stray `from quality_audit import *` cannot shadow the bot's globals.
    block = block.replace("_SIG_", "_AUDIT_SIG_").replace("_sig_tokens", "_audit_sig_tokens")
    header = (
        f"{BEGIN}\n"
        "# DO NOT EDIT THIS BLOCK BY HAND. It is copied from\n"
        "# bestgaa/main_bot_new.py by ops/sync_identity.py, because an auditor with a\n"
        "# different idea of \"which product is this?\" than the bot cannot report\n"
        "# anything true. Run: python3 ops/sync_identity.py\n"
        "# ---------------------------------------------------------------------------\n"
        "# A number in a product name is either the thing that MAKES it that product\n"
        "# (1.5 Ton, 5 Star, 128GB, 55-inch) or a spec a channel may not type at all\n"
        "# (42H playtime, 5000mAh, 1080p, 4K). Identity is brand + model + variant +\n"
        "# the numbers that change the product - never a slice of the phrase.\n"
    )
    body = re.sub(r"^# A number in a product name is either.*?\n", "", block, count=1, flags=re.S)
    return header + body + f"\n{END}\n"


def render(current: str, block: str) -> str:
    # Spacing is normalised here so writing the file twice changes nothing: `--check`
    # has to be able to run right after a sync without crying drift over a blank line.
    if BEGIN in current and END in current:
        head = current.split(BEGIN)[0].rstrip("\n")
        tail = current.split(END, 1)[1].lstrip("\n")
        return f"{head}\n\n{block}\n\n{tail}"
    anchor = "def targets_of(row) -> list[str]:"
    if anchor not in current:
        raise SystemExit("sync_identity: cannot find where to put the block in quality_audit.py")
    head, tail = current.split(anchor, 1)
    return f"{head.rstrip(chr(10))}\n\n{block}\n\n{anchor}{tail.lstrip(chr(10))}"


def main(argv: list[str]) -> int:
    block = bot_block()
    current = AUDIT.read_text(encoding="utf-8")
    wanted = render(current, block)
    if "--check" in argv:
        if wanted != current:
            print("FAIL: ops/quality_audit.py carries a DIFFERENT product-identity rule\n"
                  "      than the bot. Fix with: python3 ops/sync_identity.py")
            return 1
        print("ok: the auditor's product-identity block matches the bot's")
        return 0
    if wanted == current:
        print("ok: already in sync")
        return 0
    AUDIT.write_text(wanted, encoding="utf-8")
    print(f"written: {AUDIT.relative_to(ROOT)} now mirrors bestgaa/main_bot_new.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
